table Budget
	lineageTag: 3fb44bd5-dc68-44f9-8185-10c5b7bc0e89

	column DateID
		dataType: int64
		formatString: 0
		lineageTag: 25c1238b-62fb-4a57-8d2e-298f9d3ddea1
		summarizeBy: none
		sourceColumn: DateID

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 938c4bdb-387a-4aa3-a218-11eecd34b07f
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 4c56369d-1bc0-4b64-a37c-74acfdcbb91b
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column ID_Departement
		dataType: int64
		formatString: 0
		lineageTag: 73723dd2-3606-4da9-a93c-f3e7064913dc
		summarizeBy: none
		sourceColumn: ID_Departement

		annotation SummarizationSetBy = Automatic

	column ID_Region
		dataType: int64
		formatString: 0
		lineageTag: 3f6b165a-3756-441d-9868-8531d93b95cb
		summarizeBy: none
		sourceColumn: ID_Region

		annotation SummarizationSetBy = Automatic

	column ID_TypeDepense
		dataType: int64
		formatString: 0
		lineageTag: ec38f950-905c-47d7-841a-2f1930e80615
		summarizeBy: none
		sourceColumn: ID_TypeDepense

		annotation SummarizationSetBy = Automatic

	column MontantBudget
		dataType: double
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 0cf3d571-26ed-46cb-981b-3b5104345805
		summarizeBy: sum
		sourceColumn: MontantBudget

		annotation SummarizationSetBy = Automatic

	partition Budget = m
		mode: import
		source =
				let
				    Source = Sql.Database("DESKTOP-IKCAP89\SQLEXPRESS", "FinanceBI"),
				    dbo_Budget = Source{[Schema="dbo",Item="Budget"]}[Data],
				    #"Colonnes supprimées" = Table.RemoveColumns(dbo_Budget,{"DimDate", "DimDepartement", "DimRegion", "DimTypeDepense"})
				in
				    #"Colonnes supprimées"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

