table DimTypeDepense
	lineageTag: 992866d6-24ff-4934-89ec-ad4228bfaa08

	column ID_TypeDepense
		dataType: int64
		formatString: 0
		lineageTag: 469a3cb7-e9c6-44fc-a0cc-77d806fdc67b
		summarizeBy: none
		sourceColumn: ID_TypeDepense

		annotation SummarizationSetBy = Automatic

	column Nom_TypeDepense
		dataType: string
		lineageTag: 1184b96a-c8bf-42ee-bf0e-420826699013
		summarizeBy: none
		sourceColumn: Nom_TypeDepense

		annotation SummarizationSetBy = Automatic

	partition DimTypeDepense = m
		mode: import
		source =
				let
				    Source = Sql.Database("DESKTOP-IKCAP89\SQLEXPRESS", "FinanceBI"),
				    dbo_DimTypeDepense = Source{[Schema="dbo",Item="DimTypeDepense"]}[Data],
				    #"Colonnes supprimées" = Table.RemoveColumns(dbo_DimTypeDepense,{"Budget", "Depenses"}),
				    #"Valeur remplacée" = Table.ReplaceValue(#"Colonnes supprimées","Salaires","Payroll",Replacer.ReplaceText,{"Nom_TypeDepense"}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Valeur remplacée","Logiciels","Software",Replacer.ReplaceText,{"Nom_TypeDepense"}),
				    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1","Deplacements","Travel",Replacer.ReplaceText,{"Nom_TypeDepense"})
				in
				    #"Valeur remplacée2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

